### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by lourdas** [bisubus/yii2-apidocchm#1]
In the latest 2.0.5 release, there are a few missing icons in pages. See accompanying screenshot.
![missing-icons](https://cloud.githubusercontent.com/assets/397916/8875781/23a76394-3224-11e5-834f-3026eb0befa9.png)
Screenshot taken from KchmViewer in Linux.

**Comment by bisubus** [comment]
These icons are badges. It seems that the badge service provided PNG badges once, but for now

```
https://poser.pugx.org/yiisoft/yii2-imagine/v/stable.png
```

redirects to

```
https://poser.pugx.org/yiisoft/yii2-imagine/v/stable
```

Which is SVG image, hence it won't render properly in legacy browsers (and CHM readers are often among them).

These badges are common for all Yii2 extension documentation, you may create an issue in Yii2 repo if needed.
